tasks:
  - command: npm install && bundle install && npx gulp css && bundle exec jekyll serve

ports:
  - port: 4000
    onOpen: open-preview
    name: Website
    description: Website Preview
    visibility: public
    
github:
  prebuilds:
    master: true
    pullRequests: true
    addComment: true
    addBadge: true
    addLabel: prebuilt-in-gitpod
